### ISSUE TITLE
Automatic brackets/braces and indentation

### ISSUE THREAD

**Issue by lewisbar** [BenchR267/Get-Schwifty#11]
When enter is hit after a curly brace {, the corresponding second brace } could be automatically set and the next line could be indented, starting with four spaces, for example.
Also, when a normal brace ( or a square bracket [ is entered, the second one could immediately appear.
The first part seems easier to me, because it only requires action when enter is pressed. Maybe the second part should be moved to another issue. On the other hand, one of these features might seem incomplete without the other one.

**Comment by lewisbar** [comment]
Another related feature would be Re-Indent. Select some code, and additionally to the copy and cut options, a re-indent option appears.

**Comment by BenchR267** [comment]
That would be a great addition! For me the next steps will be to improve/rewrite the parser code to get more useful information out of it. If you would like to implement it I would be more than happy. But I also think that it might be less expensive to implement when the improvements are done

**Comment by lewisbar** [comment]
I would really be interested in trying. There are two reservations though:
- First, I need to set up my system to be able to run the latest Xcode version. The project in the current state already shows 2 errors because of my outdated Xcode/Swift version. Hopefully this week. So, waiting for the new parser sounds good as I couldn't really get started right away anyway.
- Second, I don't yet feel confident enough as a developer to be sure I can do it. I might.

So, if anyone else wants to do it, that's also okay with me. I don't want to slow this project down.

**Comment by BenchR267** [comment]
Currently I see two possible implementation strategies for this feature:
1. Observe `textViewDidChange` for a typed in `\n` and decide whether or not to insert a `\t\n}` afterwards. (That would be the more easy one)
2. Instead of using the lexer output for syntax highlighting and other 'SourceKit' related stuff we should switch to the parser output (also for coloring defined variables etc). This depends on the new parser implementation and would mean a bigger change which needs to be done anyway eventually.

I would recommend going with the first strategy. Don't doubt on yourself, I'm sure you could do it, but of course you don't have to :) There is no slowing down in the project because there is no timeline, so don't worry about that.

**Comment by lewisbar** [comment]
Okay, then I'd like to try.
As I mentioned, I can't work properly on the project right now (hopefully later this week), but I did this in a new project as a preparation. It still needs work (maintain indentation in following rows, use attributed text), but do you think this is the way to go?
```
extension ViewController: UITextViewDelegate {
    
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        guard let currentPosition = textView.selectedTextRange?.start,
            let previousPosition = textView.position(from: currentPosition, offset: -1),
            let previousRange = textView.textRange(from: previousPosition, to: currentPosition),
            let previousText = textView.text(in: previousRange) else { return true }
        var inputHasBeenModified = false
        var cursorOffset = 0
        
        switch text {
        case "\n":
            if previousText == "{" {
                textView.insertText("\n\t\n}")
                cursorOffset = 2
                inputHasBeenModified = true
            }
        case "(":
            textView.insertText("()")
            cursorOffset = 1
            inputHasBeenModified = true
        case "[":
            textView.insertText("[]")
            cursorOffset = 1
            inputHasBeenModified = true
        default:
            return true
        }
        
        // Set new cursor position
        if inputHasBeenModified, let newCursorPosition = textView.position(from: currentPosition, offset: cursorOffset) {
            textView.selectedTextRange = textView.textRange(from: newCursorPosition, to: newCursorPosition)
        }
        
        return !inputHasBeenModified
    }
}
```
The above code seems to work pretty well so far. Any feedback is welcome though. For example, I found working with text ranges a bit complicated and kind of cluttering the code. But I found no easier or nicer way so far.

One more thought: This is not as good as Xcode does it. Xcode does it like this: When you type "(" and then start typing something after that, a gray ")" appears that behaves differently depending on what you do. But I would say that's not necessary for now.

**Comment by lewisbar** [comment]
In the code above, the cursor position is set every time the function is called. If this could affect the performance, I should change that, so that all input except the relevant characters is bypassed.

**Comment by lewisbar** [comment]
Easiest way:
`default: return true
`

**Comment by lewisbar** [comment]
Okay, one more thought: This is not as good as Xcode does it. Xcode does it like this: When you type "(" and then start typing something after that, a gray ")" appears that behaves differently depending on what you do. But I would say that's not necessary for now.

**Comment by lewisbar** [comment]
I just realized I'll probably need the `previousText` for several cases. Now the first case is much more legible.
```
extension ViewController: UITextViewDelegate {
    
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        guard let selectedTextRange = textView.selectedTextRange,
            let previousPosition = textView.position(from: selectedTextRange.start, offset: -1),
            let currentPosition = textView.position(from: selectedTextRange.start, offset: 0),
            let previousRange = textView.textRange(from: previousPosition, to: currentPosition),
            let previousText = textView.text(in: previousRange) else { return true }
        var inputHasBeenModified = false
        var cursorOffset = 0
        
        switch text {
        case "\n":
            if previousText == "{" {
                textView.insertText("\n\t\n}")
                cursorOffset = 2
                inputHasBeenModified = true
            }
        case "(":
            textView.insertText("()")
            cursorOffset = 1
            inputHasBeenModified = true
        case "[":
            textView.insertText("[]")
            cursorOffset = 1
            inputHasBeenModified = true
        default:
            return true
        }
        
        // Set new cursor position
        if let newCursorPosition = textView.position(from: selectedTextRange.start, offset: cursorOffset) {
            textView.selectedTextRange = textView.textRange(from: newCursorPosition, to: newCursorPosition)
        }
        
        return !inputHasBeenModified
    }
}
```
And now I'll stop posting one comment after the other and go to bed instead ...

**Comment by lewisbar** [comment]
I can't stop! XD Here is the final version for today. You can ignore all code I posted above ... Sorry.
```
extension ViewController: UITextViewDelegate {
    
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        guard let currentPosition = textView.selectedTextRange?.start,
            let previousPosition = textView.position(from: currentPosition, offset: -1),
            let previousRange = textView.textRange(from: previousPosition, to: currentPosition),
            let previousText = textView.text(in: previousRange) else { return true }
        var inputHasBeenModified = false
        var cursorOffset = 0
        
        switch text {
        case "\n":
            if previousText == "{" {
                textView.insertText("\n\t\n}")
                cursorOffset = 2
                inputHasBeenModified = true
            }
        case "(":
            textView.insertText("()")
            cursorOffset = 1
            inputHasBeenModified = true
        case "[":
            textView.insertText("[]")
            cursorOffset = 1
            inputHasBeenModified = true
        default:
            return true
        }
        
        // Set new cursor position
        if let newCursorPosition = textView.position(from: currentPosition, offset: cursorOffset) {
            textView.selectedTextRange = textView.textRange(from: newCursorPosition, to: newCursorPosition)
        }
        
        return !inputHasBeenModified
    }
}
```

**Comment by lewisbar** [comment]
Sorry for all the notifications you probably got. I cleaned all my comments up and edited the current version into the first one.

**Comment by BenchR267** [comment]
This works really great! Something we could add here as well is ignoring input and just moving the cursor if `)` is typed and the next character already is a `)` (for `}`, `]` as well). But really great work!

**Comment by lewisbar** [comment]
Thank you!
I think your suggestion wouldn't work well with nested brackets like in
`print(f(x))`
You would have to scan the whole document for open and closed brackets to decide when a bracket should be ignored.
I would instead assume the user doesn't type a bracket that's already there.

**Comment by lewisbar** [comment]
I'm not sure.

**Comment by lewisbar** [comment]
Actually, I think your suggestion makes sense, I changed my mind. :)
There may be rare cases when this is not what the user wants. But I guess that's okay.

**Comment by BenchR267** [comment]
Yeah, scanning the whole document would be much easier if this would work with the parser output instead of strings, but for the first implementation this would be a great addition :)

**Comment by lewisbar** [comment]
The update to Sierra worked!
I'll open the pull request once I built it in.
For now I'll concentrate on making the whole thing work properly, whenever I find some time. After that, I'll see how I can get that into your project.
If you want to see the current state: https://github.com/lewisbar/CodingTextView.

I found that quotes "" are also a case for this issue. They are bit harder though, as the first and the second one is the same. But I'm already handling that by counting the number of "s in the whole document, which works fine.

**Comment by ghost** [comment]
Be sure to check whether Undo still works. That's tricky when modifying text in this callback, IIRC.

**Comment by lewisbar** [comment]
I have not worked with undo yet. Clicking the undo key in the iPad simulator or shaking my iPhone doesn't seem to do anything. I guess undo has yet to be implemented?

**Comment by BenchR267** [comment]
Mh, I think undo is not working in Get Schwifty because the text is always replaced after being tokenized by the lexer. This is another issue in my eyes, but something that should be tackled sometime.

**Comment by lewisbar** [comment]
Okay. The question is: Do I need to pay attention to anything or can can we care about undo later?

**Comment by BenchR267** [comment]
You can totally ignore it for now :)

**Comment by lewisbar** [comment]
That's good to know. :)

**Comment by BenchR267** [comment]
Thanks again for your great contribution!

**Comment by uliwitness** [comment]
Can you use styles? Xcode shows brackets it auto-adds in grey. If you type a ")" right before a grey ")", it just replaces it (assuming you reflexively typed the bracket yourself), otherwise the grey bracket becomes permanent.

**Comment by lewisbar** [comment]
My addition doesn't distinguish between automatically added brackets and typed brackets. It just tries to figure out if a bracket makes sense. This has pros and cons, in my opinion.

**Comment by BenchR267** [comment]
I think this was the best solution for now, we could add different states later. But this should not be the highest priority in my eyes :)
